### ISSUE TITLE
CUDA error 700: an illegal memory access was encountered

### ISSUE THREAD

**Issue by jamesw3712** [catboost/catboost#1946]
Problem: Getting an illegal memory access was encountered error at random trial with optuna
catboost version: 1.0.3
Operating System: Windows
CPU: Intel i5 6600K
GPU: GTX 1070

Application terminated with error: PyInit__catboost+1995996 (0x7FF8FB1B9B0C)
??+0 (0x7FF8FAB2999E)
??+0 (0x7FF8FADAEF2D)
??+0 (0x7FF8FADAF472)
PyInit__catboost+11498905 (0x7FF8FBAC9BC9)
PyInit__catboost+11467936 (0x7FF8FBAC22D0)
PyInit__catboost+11468973 (0x7FF8FBAC26DD)
??+0 (0x7FF8FADDAC1B)
??+0 (0x7FF8FADD1701)
PyInit__catboost+23341352 (0x7FF8FC614F58)
BaseThreadInitThunk+20 (0x7FF9631B7034)
RtlUserThreadStart+33 (0x7FF964862651)

(class TCatBoostException) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:230: CUDA error 700: an illegal memory access was encountered

Thanks!

**Comment by ek-ak** [comment]
Hello! Thank you for bug report. Could you provide a reproducing example?

**Comment by jamesw3712** [comment]
Sure.  im training with the following params and it fails before the fitting process is finished

{'iterations': 121, 'loss_function': 'Logloss', 'learning_rate': 0.3525168293462534, 'l2_leaf_reg': 0.023699684814434126, 'border_count': 118, 'depth': 1, 'boosting_type': 'Plain', 'bootstrap_type': 'Poisson', 'leaf_estimation_backtracking': 'Armijo', 'min_data_in_leaf': 7, 'one_hot_max_size': 11, 'has_time': True, 'random_seed': 42, 'task_type': 'GPU', 'devices': '0', 'subsample': 0.2769540222341547, 'auto_class_weights': 'None'}
getting catboost struff

 reg = CatBoostClassifier(**param, cat_features=categorical_features_indices, verbose=True)
  reg.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=3, early_stopping_rounds=100)
  y_pred = reg.predict(X_test)
  score = roc_auc_score(y_test, y_pred)

**Comment by jamesw3712** [comment]
here is the entire method for more context:

`def objective(trial):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    param = {
        "iterations": trial.suggest_int("iterations", 100, iterations),
        "loss_function": trial.suggest_categorical("loss_function", ["Logloss"]),
        "learning_rate": trial.suggest_loguniform("learning_rate", 1e-5, 1e0),
        "l2_leaf_reg": trial.suggest_loguniform("l2_leaf_reg", 1e-2, 1e0),
        "border_count": trial.suggest_int("border_count", 2, 256),
        "depth": trial.suggest_int("depth", 1, 8),
        "boosting_type": trial.suggest_categorical("boosting_type", ["Ordered", "Plain"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "Poisson"]),
        "leaf_estimation_backtracking": trial.suggest_categorical("leaf_estimation_backtracking",
                                                                  ["AnyImprovement", "Armijo"]),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 1, 20),
        "one_hot_max_size": trial.suggest_int("one_hot_max_size", 2, 20),
        'has_time': True,
        'random_seed': 42,
        'task_type': "GPU",
        'devices': '0'
    }

    if param["bootstrap_type"] == "Bayesian":
        param["bagging_temperature"] = trial.suggest_float("bagging_temperature", 0, 10)
    elif param["bootstrap_type"] == "Bernoulli" or param["bootstrap_type"] == 'Poisson':
        param["subsample"] = trial.suggest_float("subsample", 0.1, 1)

        if param["loss_function"] == "Logloss":
            param["auto_class_weights"] = trial.suggest_categorical("auto_class_weights",
                                                                    ["None", "Balanced", "SqrtBalanced"])

    print(param)
    print("getting catboost struff")
    reg = CatBoostClassifier(**param, cat_features=categorical_features_indices, verbose=True)
    print("Fitting")
    reg.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=3, early_stopping_rounds=100)
    print("done fitting")
    y_pred = reg.predict(X_test)
    print("predicting")
    score = roc_auc_score(y_test, y_pred)
    print("Getting score and returning")
    return score`

**Comment by jamesw3712** [comment]
Here is the method for more context:
[reproduceMethod.txt](https://github.com/catboost/catboost/files/7675396/reproduceMethod.txt)

**Comment by Insaned79** [comment]
I seem to have the same error on the same GPU on Linux:
catboost version: 1.0.3
Operating System: Linux Mint 19.3
CPU: AMD Ryzen 7 3700X
GPU: GTX 1070
uncaught exception:
    address -> 0x482ec060410
    what() -> "catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 700: an illegal memory access was encountered"
    type -> TCatBoostException


```
cat = CatBoostRegressor(
            iterations=10000,
            task_type='GPU',     
            use_best_model=True,
            loss_function='MAE')    

cat.fit(df_X_train,y_train,  
            verbose = 0,
            plot=True,
            cat_features=list_category_features,
            eval_set=(df_X_test, y_test))
```

**Comment by ek-ak** [comment]
> I seem to have the same error on the same GPU on Linux:

Hello! It is some general error report, so more likely it is another bug, please create separate issue (with a reproducer pool, if it is available).

**Comment by amitred** [comment]
I'm also getting the same error, was anyone able to find a work around the bug?

**Comment by thyllmuller** [comment]
I got this as well:

```
Application terminated with error: PyInit__catboost+1848348 (0x7FFB7AC493FC)
??+0 (0x7FFB7A6F2F2E)
??+0 (0x7FFB7A78C825)
??+0 (0x7FFB7A794D7B)
PyInit__catboost+9876147 (0x7FFB7B3F1293)
PyInit__catboost+9853656 (0x7FFB7B3EBAB8)
PyInit__catboost+9855211 (0x7FFB7B3EC0CB)
??+0 (0x7FFB7A8DD5DD)
PyInit__catboost+13349300 (0x7FFB7B741194)
BaseThreadInitThunk+16 (0x7FFC61CA54E0)
RtlUserThreadStart+43 (0x7FFC6312485B)

(class TCatBoostException) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 700: an illegal memory access was encountered
```

**Comment by andrey-khropov** [comment]
MAE-specific problem has been fixed in master and will be included in the next release: https://github.com/catboost/catboost/issues/1983#issuecomment-1016251960
