### ISSUE TITLE
CatBoostRegressor on GPU with loss_function='MAE' results in CUDA error 700: an illegal memory access was encountered

### ISSUE THREAD

**Issue by amitred** [catboost/catboost#1983]
Problem: Getting a CUDA error 700: an illegal memory access was encountered while using CatBoostRegressor on GPU with loss_function='MAE' 
catboost version: '1.0.4'
Operating System: Ubuntu 18.04.5 LTS
CPU: Intel Haswell 32 vCPU (GCP)
GPU: 4 x Tesla T4 (GCP)

Error Message:
Application terminated with error: ??+0 (0x7FBBB2624EEF)
??+0 (0x7FBBB3A2327B)
??+0 (0x7FBBB3A24608)
??+0 (0x7FBBB27CE107)
??+0 (0x7FBBB27CDFB7)
??+0 (0x7FBCE64B76DB)
clone+63 (0x7FBCE583371F)

(TCatBoostException) catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 700: an illegal memory access was encountered
uncaught exception:
    address -> 0x3c4e75a0410
    what() -> "catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 700: an illegal memory access was encountered"
    type -> TCatBoostException
Aborted (core dumped)

Issue:
This error occurs while using CatBoostRegressor(loss_function='MAE'), if I use the default loss_function i.e. CatBoostRegressor(loss_function='RMSE') I'm able to complete the training.
I'm also using eval_metric='MAE' and that does not cause any issue.

There have been similar issues in the past with different variable values for Catboost models, I didn't find any solution for them so raising this new issue.

Thanks!

**Comment by kizill** [comment]
This issue is fixed in master - for now, try to set `boosting_type='Ordered'` in one run and `leaf_estimation_method='Gradient'` in another and select, which one gives you the best quality :)

**Comment by amitred** [comment]
I tried using both the suggestion in separate runs; 
`boosting_type='Ordered'` : Did not work, and ran into the same error
`leaf_estimation_method='Gradient'` : Did work however the learning is quite slow

As mentioned in your message, if this issue has already been fixed in master, can I install it in PyPI? Thanks.

**Comment by kizill** [comment]
Sorry, i've mistyped! I meant `boosting_type='Plain'`!

**Comment by amitred** [comment]
The `boosting_type='Plain'` did work with minor changes on my end for a sample run. However while running on complete dataset I'm again getting the same error:

Application terminated with error: ??+0 (0x7FE401F28EEF)
??+0 (0x7FE40332727B)
??+0 (0x7FE403328608)
??+0 (0x7FE4020D2107)
??+0 (0x7FE4020D1FB7)
??+0 (0x7FE4B05646DB)
clone+63 (0x7FE4AF8E071F)

(TCatBoostException) catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 700: an illegal memory access was encountered
uncaught exception:
    address -> 0x264181a0410
    what() -> "catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 700: an illegal memory access was encountered"
    type -> TCatBoostException
Aborted (core dumped)

**Comment by amitred** [comment]
I'm using this command to initialize the Catboost Regressor, hope this helps:
```
cat = CatBoostRegressor(iterations=10000,
                                             task_type='GPU',
                                             depth=6,
                                             learning_rate=0.025,
                                             thread_count=-1,
                                             l2_leaf_reg=10,
                                             loss_function='MAE',
                                             boosting_type='Plain',
                                             eval_metric = 'MAE',
                                             posterior_sampling=False,
                                       )
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @amitred ✋ 
we fixed a bug that led to `cuda error 700` for small datasets
fde84b57aa7e451cc7318ad07ffe78326be55505
if the bug is still there for you, then could you please share with us an end-to-end reproducer, and reopen this issue?
many thanks for using catboost, and cheers 😃
