### ISSUE TITLE
Seeing this error when using 100 or 1000 iterations but not 10: CUDA error 100: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by EvanZ** [catboost/catboost#2551]
Problem: I'm trying to automate my catboost model training by using Amazon EMR to run my scripts. Everything seems to be working fine with GPU training as long as I don't set iterations much greater than 10 (like 100 or 1000). The problem is 10 is too low and results in a much worse model. I typically use 1000 iterations for my "final" models. The error I'm seeing in the logs looks like this:

```
columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x[col] = "UNK"
Traceback (most recent call last):
  File "/home/hadoop/boosting_behavior_models/train_classifier.py", line 121, in <module>
    model.fit(X=train_x, y=train_y, eval_set=test_pool, plot_file='training_plot.html')
  File "/home/hadoop/boosting_behavior_models/.env/lib/python3.8/site-packages/catboost/core.py", line 5100, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/home/hadoop/boosting_behavior_models/.env/lib/python3.8/site-packages/catboost/core.py", line 2319, in _fit
    self._train(
  File "/home/hadoop/boosting_behavior_models/.env/lib/python3.8/site-packages/catboost/core.py", line 1723, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4624, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4673, in _catboost._CatBoost._train
_catboost.CatBoostError: /src/catboost/catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 100: no CUDA-capable device is detected
Command exiting with ret '1'
```

I have no clue why such an error would arise. Is it possible that catboost only uses the GPU when iters > N? Maybe it's actually using the CPU when the iterations are set to 10 so I only see this error when it starts to use the GPU? Actually now that I'm thinking about it, that doesn't make sense either because when I tried to train the model with just a small amount of training data but used 1000 iters, it worked as well. So I am totally befuddled here.

catboost version: 1.2.1
Operating System: Amazon Linux
CPU:
GPU: Tesla V100-SXM2-16GB (Amazon p3.2xlarge instance)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @EvanZ 

thank you for using catboost!

could you please try the solution from https://github.com/catboost/catboost/issues/2217 ?
it might be related

**Comment by EvanZ** [comment]
@Evgueni-Petrov-aka-espetrov Hi! Yes, it appears to be the same problem where I can run the exact same code more than once on EMR and sometimes it works but most of the time it fails and results in this CUDA error. I looked at #2217 but the solution seems to be making some changes to docker, which I am not using, so I'm not sure how to fix this. I am just using boto3 to launch my Python and shell scripts to EMR. Any thoughts?

**Comment by EvanZ** [comment]
I'm going to close this issue as it turns out the practical solution is to use an EC2 instance with multiple gpus. Perhaps it was just a memory issue? Regardless, hope this helps someone who might run into a similar problem.
