### ISSUE TITLE
Catboost requesting 17gb of memory on a relatively small dataset

### ISSUE THREAD

**Issue by Alescontrela** [catboost/catboost#405]
When fitting CatBoostRegressor on a (relatively) small dataset, 5000 rows by 5000 columns with 32-bit float values, I get the following memory error: 
```shell
uncaught exception:
    address -> 0x107925988
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 17476.96875; Free 2255.542871"
    type -> NCudaLib::TOutOfMemoryError
```

I would understand if I received this error when training on a much larger dataset with heavier datatypes, but it doesn't make much sense in the context of my small dataset. 

Even when I limit the categorical complexity through `max_ctr_complexity`, I receive the above error. The parameters are set as follows:

```python
cb_param_grid = {
            "iterations":500,
            "learning_rate":0.05,
            "depth":10,
            "random_seed" : random_seed,
            "bagging_temperature" : 0.7,
            "metric_period" : 50,
            "task_type":'GPU',
            "max_ctr_complexity":2
            }
```

It woulld be greatly appreciated if someone from the Catboost team could explain why so much memory is needed to train on such a small dataset.

Problem: {Out of memory error}
catboost version: {0.9.1.1}
Operating System: {Ubuntu 16.04 }
GPU: {GPU}

**Comment by Alescontrela** [comment]
O.k. so I set the following parameters: 

```
cb_param_grid = {
            "max_ctr_complexity":1,
            "boosting_type":"Plain",
            "logging_level":"Debug",
            "max_bin":128,
            "iterations":500,
            "learning_rate":0.05,
            "depth":10,
            "random_seed" : random_seed,
            "bagging_temperature" : 0.3,
            "metric_period" : 50,
            "task_type":'GPU'
            }
```


The provided output was as follows:

```
No catFeatures for ctrs found and don't look ahead is disabled. Fallback to one permutation
```

as well as: 

```
uncaught exception:
    address -> 0x10791ac48
    what() -> "catboost/cuda/cuda_lib/cuda_base.cpp:16: CUDA error: out of memory 2"
    type -> TCatboostException

```

Also, when I set `max_bin` to 16 or 32, I still get the above error messages.

**Comment by Alescontrela** [comment]
I should add that sometimes it works, sometimes it doesn't. In fact, most of the time training is cut short with the following error message: 

```
No catFeatures for ctrs found and don't look ahead is disabled. Fallback to one permutation
uncaught exception:
    address -> 0x1079195c8
    what() -> "catboost/cuda/cuda_lib/cuda_base.cpp:16: CUDA error: out of memory 2"
    type -> TCatboostException
Aborted (core dumped)

```

**Comment by Noxoomo** [comment]
Hi!


> uncaught exception:
>     address -> 0x10791ac48
>     what() -> "catboost/cuda/cuda_lib/cuda_base.cpp:16: CUDA error: out of memory 2"
>     type -> TCatboostException
> 

This is because of allocation of high amount of memory on the start, seems like some other applications allocated before catboost. If you'll decrease "gpu_ram_part"  to 0.9 I think this solve this issue


> Could you explain why changing the max_ctr_complexity allowed the model to train on GPU?

Seems like there is a bug somewhere. 

Do you pass any categorical features to CatBoost? because from logs it seems like you don't have cat features => changing max_ctr_complexity should not affect memory consumption at all.



Could you run again "boosting_type":"Plain" and  "boosting_type":"Ordered". Ordered boosting has high memory consumption, but it should not be so big for you dataset

**Comment by Alescontrela** [comment]
Hi @Noxoomo , 
When training the model with `"boosting_type":"Ordered"`, the process terminated with the same "out of memory" error as mentioned above. Additionally, when I remove `"max_ctr_complexity":1`, I again get the same error as above. As you said in your comment, `max_ctr_complexity` should not affect training because I am not passing the `cat_features` parameter.

When training with the parameters shown below, I sometimes achieve success but most of the time my model fails to initialize training:

```python
cb_param_grid = {
            "boosting_type":"Plain",
            "iterations":500,
            "learning_rate":0.03,
            "depth":5,
            "random_seed" : random_seed,
            "bagging_temperature" : 0.1,
            "metric_period" : 50,
            "task_type":'GPU',
            "max_ctr_complexity":1,
            "gpu_ram_part":0.9,
            "max_bin":32
            }
```

Just as a sanity check, CatBoostRegressor should be imported with `from catboost import CatBoostRegressor` even when training on GPU, correct?

**Comment by Noxoomo** [comment]
I found what goes wrong.

You have many features (5k) and deep trees (depth 10), so CatBoost needs too many memory to store statistics necessary for searching for the best splits (we could need  approximately (1^depth) * feature_count * max_bin *8 bytes memory for boosting_type: Plain).  This is our trade-off to learn fast, so it'll not be fixed in a near future (we'll add fallbacks for more computations instead of caching in future, but it's not simple task) 

So:
1) "boosting_type":"Plain" is the only way to go, for "boosting_type":"Ordered" you'll need significantly more memory
2) max_bin: 128,  depth 8 and boosting-type Plain should work with 2.5GB of memory, so your depth 5 max_bin: 32 should also run fine. If you have  "CUDA error: out of memory 2" exception, that this means we can't allocate memory on start. I don't know the exact reason, but: 1) there could be other applications allocating memory in parallel 2) CUDA just can't allocate amount of memory we requested, so try decrease "gpu_ram_part" part even more

**Comment by Alescontrela** [comment]
Hi, 
is it (1^depth) or (2^depth)? (since we make a split at each node). 

I believe I fixed the `CUDA error: out of memory 2` error by closing all applications while running training. My 970GTX allocates ~60-70mb of memory to each open application, so I closed them to free up as much space as possible. Doing this and keeping `gpu_ram_part` on 0.9 seems to work.
